import { notFound } from 'next/navigation';

const API_BASE = process.env.API_URL || process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api/v1';

async function getShareCard(shareUrl: string) {
  try {
    const res = await fetch(`${API_BASE}/share/card/${shareUrl}`, { cache: 'no-store' });
    if (!res.ok) return null;
    return res.json();
  } catch {
    return null;
  }
}

export default async function PublicSharePage({ params }: { params: Promise<{ shareUrl: string }> }) {
  const { shareUrl } = await params;
  const card = await getShareCard(shareUrl);
  if (!card) notFound();

  return (
    <div className="min-h-screen bg-[#050508] flex items-center justify-center p-6">
      <div className="w-full max-w-2xl">
        {/* Card */}
        <div className="glass-strong rounded-3xl p-8 shadow-2xl relative overflow-hidden">
          {/* Gradient orbs */}
          <div className="absolute -top-20 -right-20 w-64 h-64 rounded-full bg-indigo-500/10 blur-3xl pointer-events-none" />
          <div className="absolute -bottom-20 -left-20 w-64 h-64 rounded-full bg-purple-500/10 blur-3xl pointer-events-none" />

          {/* Brand */}
          <div className="flex items-center gap-2 mb-8">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-white text-sm font-bold">CT</div>
            <span className="font-semibold text-sm">CareerTwin</span>
            <span className="ml-auto text-xs text-muted px-2 py-1 rounded-full bg-white/5">AI Career Intelligence</span>
          </div>

          <h1 className="text-2xl font-bold mb-1 gradient-text">{card.title}</h1>
          <p className="text-muted text-sm mb-8">Shared career profile — {new Date(card.createdAt || Date.now()).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>

          {/* Data */}
          {card.data && (
            <div className="space-y-4">
              {Object.entries(card.data as Record<string, unknown>).map(([key, value]) => {
                if (value === null || value === undefined) return null;
                const label = key.replace(/([A-Z])/g, ' $1').trim();
                return (
                  <div key={key} className="flex items-center justify-between py-3 border-b border-white/5 last:border-0">
                    <span className="text-sm text-muted capitalize">{label}</span>
                    <span className="text-sm font-semibold">
                      {typeof value === 'number'
                        ? value > 1000 ? `$${(value / 1000).toFixed(0)}K` : `${value}${key.toLowerCase().includes('score') || key.toLowerCase().includes('percent') ? '%' : ''}`
                        : Array.isArray(value)
                        ? (value as string[]).slice(0, 3).join(', ')
                        : String(value)}
                    </span>
                  </div>
                );
              })}
            </div>
          )}

          {/* CTA */}
          <div className="mt-8 p-4 rounded-2xl bg-gradient-to-r from-indigo-500/10 to-purple-500/10 border border-indigo-500/20 text-center">
            <p className="text-sm text-muted mb-2">Build your own AI Career Twin</p>
            <a href="/" className="inline-block px-6 py-2.5 rounded-xl bg-gradient-to-r from-indigo-500 to-purple-600 text-white text-sm font-semibold hover:opacity-90 transition-opacity">
              Get Started Free →
            </a>
          </div>
        </div>

        <p className="text-center text-xs text-muted mt-4">
          Generated by CareerTwin AI · <a href="/" className="text-indigo-400 hover:underline">careertwin.ai</a>
        </p>
      </div>
    </div>
  );
}
